### ISSUE TITLE
unzip in readme does not work

### ISSUE THREAD

**Issue by tobigithub** [nbehrnd/aRMSD-portable#1]
The recommendation in readme to recombine does not work under Ubuntu 16
````
 zip -s 0 test.zip --out unsplit.zip
        zip warning: cannot update a split archive (use --out option)

zip error: Invalid command arguments (test.zip)

````
this works:
````
 zip -F test.zip --out unsplit.zip

````
then
````
unzip unsplit.zip
````

**Comment by nbehrnd** [comment]
Yes, your approach works.

The command in the corresponding readme was derived from _a_ section in the man pages about zip (attached screen photo, version 3.0, 16 June 2008).  Since it equally seemed to match zip's info page (about 13 to 14%, same date) and worked on a separate test prior deposit of the data, too, I speculate the rendering of two "-" /n-dash into one m-dash contributed to this bump.

![splitzip](https://user-images.githubusercontent.com/19709084/50032943-6d8c2300-ffee-11e8-9d27-719120f9e3d5.png)
